// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7UKHw_3-8ckHamZxIobWYxqhMoon9bOY',
    appId: '1:363836045063:web:a499ebd524da37486477a2',
    messagingSenderId: '363836045063',
    projectId: 'formafit-2febc',
    authDomain: 'formafit-2febc.firebaseapp.com',
    storageBucket: 'formafit-2febc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnfhy57ysPMsYHGY-imqA077v3u0WsAf4',
    appId: '1:363836045063:android:6c801f475fab1bdd6477a2',
    messagingSenderId: '363836045063',
    projectId: 'formafit-2febc',
    storageBucket: 'formafit-2febc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzNxPwjJi1vNais4yyNChMF7xmnyuQ694',
    appId: '1:363836045063:ios:fa5b77e6356998636477a2',
    messagingSenderId: '363836045063',
    projectId: 'formafit-2febc',
    storageBucket: 'formafit-2febc.appspot.com',
    iosBundleId: 'com.example.formafit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzNxPwjJi1vNais4yyNChMF7xmnyuQ694',
    appId: '1:363836045063:ios:fa5b77e6356998636477a2',
    messagingSenderId: '363836045063',
    projectId: 'formafit-2febc',
    storageBucket: 'formafit-2febc.appspot.com',
    iosBundleId: 'com.example.formafit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7UKHw_3-8ckHamZxIobWYxqhMoon9bOY',
    appId: '1:363836045063:web:e3c8dc62ead2d2b26477a2',
    messagingSenderId: '363836045063',
    projectId: 'formafit-2febc',
    authDomain: 'formafit-2febc.firebaseapp.com',
    storageBucket: 'formafit-2febc.appspot.com',
  );

}